### ISSUE TITLE
typo in UFO interface for K6bar

### ISSUE THREAD

**Issue by dude-jan** [FeynRules/FeynRules#2]
I always get K6 instead of K6Bar in the color structure of a vertex whenever I write down a vertex involving explicitly the K6bar tensor.

It seems that there is a typo in
https://github.com/FeynRules/FeynRules/blob/97b0798740a12fc1dbbe529991d2a41778449926/Interfaces/UFO/PYIntVertices.m#L1369
I think it should read `C$K6bar` also on the right hand side.

**Comment by BFuks** [comment]
Dear Jan,

I think that you are correct. I am adding Claude to the thread to verify whether there was any reason for this when we implemented it 15 years ago. If not, then I will update the code.

Cheers,

Benjamin

**Comment by BFuks** [comment]
Dear Jan, 

Yes, I confirm, that is correct. It should be C$K6bar on both sides.

Thanks for pointing this out!

Cheers,

Claude

> Am 12.12.2024 um 16:21 schrieb Benjamin Fuks ***@***.***>:
> 
> Dear Jan,
> 
> I think that you are correct. I am adding Claude to the thread to verify whether there was any reason for this when we implemented it 15 years ago. If not, then I will update the code.
> 
> Cheers,
> 
> Benjamin
>

**Comment by BFuks** [comment]
Hi Claude,

Thanks for confirming, and thanks again to Jan fior letting us know. I have pushed the fix. Note that the bug was not present in feynrules-dev-bsm. 

Cheers,

Benj

**Comment by dude-jan** [comment]
Thanks for the fast reply!
